name: Frontend build check


on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React repo
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      
      - name: Build project
        working-directory: frontend
        env:
          VITE_APP_BACKEND_URL: ${{ vars.VITE_APP_BACKEND_URL }}
        run: |
          npm ci
          npm run build