name: Deploy frontend for Watch Together app site


on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: jothamteshome/infra-hub/.github/workflows/deploy-static-site.yml@deploy-static-site-latest
    permissions:
      id-token: write
      contents: read
    with:
      working_directory: frontend
      build_env: |
        VITE_APP_BACKEND_URL=${{ vars.VITE_APP_BACKEND_URL }}
    secrets:
      AWS_STATIC_SITE_ROLE_TO_ASSUME: ${{ secrets.AWS_STATIC_SITE_ROLE_TO_ASSUME }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
    