name: Deploy Frontend for youtube sync app site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: jothamteshome/reusable-github-actions-workflows/.github/workflows/deploy-static-site.yml@deploy-static-site-latest

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}